modLoader="javafml"
loaderVersion="[35,36, )"
license="Apache-2.0"
issueTrackerURL="https://github.com/xElementzx/EnchantingBooks/issues"

[[mods]]
modId="enchantingbooks"
version="${version}"
displayName="Enchanting Books"
displayURL="https://elementz.me/"
logoFile="logo.png"
authors="xElementzx, LX_Gaming"
description='''

This is a mod designed to give more variety to the vanilla enchanted books by adding extra types with greater enchantability.

Source - https://github.com/xElementzx/EnchantingBooks
'''