modLoader="javafml"
loaderVersion="[35,)"
license="Apache-2.0"
issueTrackerURL="https://github.com/xElementzx/EnchantingBooks/issues"

[[mods]]
modId="enchantingbooks"
version="${version}"
displayName="Enchanting Books"
displayURL="https://elementz.me/"
logoFile="logo.png"
authors="xElementzx, LX_Gaming"
description='''

This is a mod designed to give more variety to the vanilla enchanted books by adding extra types with greater enchantability.

Source - https://github.com/xElementzx/EnchantingBooks
'''

[[dependencies.enchantingbooks]]
modId="forge"
mandatory=true
versionRange="[35.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.enchantingbooks]]
modId="minecraft"
mandatory=true
versionRange="[1.16,)"
ordering="NONE"
side="BOTH"